name: 35 - Workflow call simple-java

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: master

jobs:
  call-workflow-branch-ref:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: Soorya8docker
      branch: master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  DEV:
    runs-on: ubuntu-latest
    steps:
    - name: Printing
      run: echo "${{ inputs.branch }}"
