name: 35 - Workflow call simple-java

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: master

jobs:
  trigger_reusable:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      input: ${{ inputs.branch }}
