name: 35 - Workflow call simple-java

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: master
    secrets:
      MY_SECRET: Testing

jobs:
  trigger_reusable:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      some-input: ${{ inputs.branch }}
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
