name: 35 - Workflow call simple-java

on:
  workflow_dispatch:

jobs:
  call-workflow-branch-ref:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: Soorya8docker
      branch: master
      repository: Soorya8docker/simple-java-maven-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
