name: Workflow caller - simple-java-maven-app

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        default: Soorya8docker
      repo:
        required: true
        type: string
        default: simple-java-maven-app
      branch:
        required: true
        type: string
        default: master
      temp:
        required: true
        type: string
        default: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
      

jobs:
  call-workflow-branch-ref:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@${{ inputs.branch }}
    with:
      username: ${{ inputs.username }}
      branch: ${{ inputs.branch }}
      repo: ${{ inputs.repo }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
