name: Workflow caller - ALL3
on:
  workflow_dispatch:     

jobs:
  call-workflow-simple-java-maven-app:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: Soorya8docker
      branch: master
      repo: simple-java-maven-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
  call-workflow-javaparser-maven-sample:
    uses: Soorya8docker/javaparser-maven-sample/.github/workflows/reusable.yaml@master
    with:
      username: Soorya8docker
      branch: master
      repo: javaparser-maven-sample
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-AmexProject:
    uses: Soorya8docker/AmexProject/.github/workflows/reusable.yaml@main
    with:
      username: Soorya8docker
      branch: main
      repo: AmexProject
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
