name: Workflow caller

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string


jobs:
  call-workflow-branch-ref:
    uses: ${{ inputs.username }}/${{ inputs.repo }}/.github/workflows/reusable.yml@master
    with:
      username: ${{ inputs.username }}
      branch: ${{ inputs.branch }}
      repo: ${{ inputs.repo }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
