name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true
      Workflow:
        description: 'Enter Workflow name'
        type: string
        required: true
      RepoName:
        description: 'Enter Repository name'
        type: string
        required: true

jobs:
  call-workflow:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/DEVBuild.yml@master
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       ref: ${{ inputs.Branch }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -X package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
