name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true
      Workflow:
        description: 'Enter Workflow name'
        type: string
        required: true
      RepoName:
        description: 'Enter Repository name'
        type: string
        required: true

jobs:
  call-workflow:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/DEVBuild.yml@main
