name: Workflow caller - kasi84/java-maven-app
on:
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
        default: kasi84
      repo:
        required: true
        type: string
        default: java-maven-app
      branch:
        required: true
        type: string
        default: master

jobs:
  call-workflow-branch-ref:
    uses: kasi84/E-commerce-project-springBoot/.github/workflows/reusable.yaml@master2
    with:
      username: ${{ inputs.username }}
      branch: ${{ inputs.branch }}
      repo: ${{ inputs.repo }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
