name: Workflow Caller - Optional Repo

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Select the username'
        required: true
        type: choice
        options:
          - Soorya8docker
        default: Soorya8docker
      repo:
        description: 'Select the repo name'
        required: true
        type: choice
        options:
          - simple-java-maven-app
          - javaparser-maven-sample
          - AmexProject
          - java-maven-app
          - ALL
      branch:
        description: 'Select the branch name'
        required: true
        type: choice
        options:
          - master
          - main

jobs:
  call-workflow-Soorya8docker:
    if: ${{ inputs.repo != 'ALL' }}
    #uses: {{ inputs.username }}/${{ inputs.repo }}/.github/workflows/reusable.yml@${{ inputs.branch }}
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: ${{ inputs.username }}
      branch: ${{ inputs.branch }}
      repo: ${{ inputs.repo }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
  call-workflow-simple-java-maven-app:
    if: ${{ inputs.repo == 'ALL' }}
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: Soorya8docker
      branch: master
      repo: simple-java-maven-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-javaparser-maven-sample:
    if: ${{ inputs.repo == 'ALL' }}
    needs: call-workflow-simple-java-maven-app
    uses: Soorya8docker/javaparser-maven-sample/.github/workflows/reusable.yaml@master
    with:
      username: Soorya8docker
      branch: master
      repo: javaparser-maven-sample
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  
  call-workflow-kasi84-java-maven-app:
    if: ${{ inputs.repo == 'ALL' }}
    needs: call-workflow-javaparser-maven-sample
    uses: kasi84/java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: kasi84
      branch: master
      repo: java-maven-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-AmexProject:
    if: ${{ inputs.repo == 'ALL' }}
    needs: call-workflow-kasi84-java-maven-app
    uses: Soorya8docker/AmexProject/.github/workflows/reusable.yaml@main
    with:
      username: Soorya8docker
      branch: main
      repo: AmexProject
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
