name: Review Workflow

on:
  workflow_dispatch:


jobs:
   PROD_Deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: PROD Deployment with input
      shell: bash
      run: echo "testing"
