name: Workflow Caller - Stat2

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Select the username'
        required: true
        type: choice
        options:
          - Soorya8docker
          - kasi84
        default: Soorya8docker
      repo:
        description: 'Select the repo name'
        required: true
        type: choice
        options:
          - simple-java-maven-app
          - javaparser-maven-sample
          - AmexProject
          - java-maven-app
      branch:
        description: 'Select the branch name'
        required: true
        type: choice
        options:
          - master
          - main

jobs:    
  call-workflow-simple-java-maven-app:
    if: ${{ inputs.repo == 'simple-java-maven-app' }}
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: Soorya8docker
      branch: master
      repo: simple-java-maven-app
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  call-workflow-javaparser-maven-sample:
    needs: call-workflow-simple-java-maven-app
    if: ${{ needs.call-workflow-simple-java-maven-app.result == 'success' }}
    uses: Soorya8docker/javaparser-maven-sample/.github/workflows/reusable.yaml@master
    with:
      username: Soorya8docker
      branch: master
      repo: javaparser-maven-sample
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
