name: Workflow Caller - Any Repo

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Select the username'
        required: true
        type: choice
        options:
          - Soorya8docker
          - kasi84
        default: Soorya8docker
      repo:
        description: 'Select the repo name'
        required: true
        type: choice
        options:
          - simple-java-maven-app
          - javaparser-maven-sample
          - AmexProject
          - java-maven-app
      branch:
        description: 'Select the branch name'
        required: true
        type: choice
        options:
          - master
          - main

jobs:
  call-workflow-branch-ref:
    uses: Soorya8docker/simple-java-maven-app/.github/workflows/reusable.yml@master
    with:
      username: ${{ inputs.username }}
      branch: ${{ inputs.branch }}
      repo: ${{ inputs.username }}/${{ inputs.repo }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
